# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- feature/*

pool:
  vmImage: ubuntu-20.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    curl https://cdn.shiftleft.io/download/sl > $(Agent.HomeDirectory)/sl && chmod a+rx $(Agent.HomeDirectory)/sl
    $(Agent.HomeDirectory)/sl analyze --app sl-vue-az --wait --tag branch=$(Build.SourceBranchName) --js --cpg .
  displayName: 'ShiftLeft NG SAST'
  workingDirectory: '$(Build.SourcesDirectory)'
  env:
    SHIFTLEFT_ACCESS_TOKEN: $(SHIFTLEFT_ACCESS_TOKEN)

- script: |
    $(Agent.HomeDirectory)/sl check-analysis --app sl-vue-az
  displayName: 'ShiftLeft check analysis'
  workingDirectory: '$(Build.SourcesDirectory)'
  continueOnError: "true"
  env:
    SHIFTLEFT_ACCESS_TOKEN: $(SHIFTLEFT_ACCESS_TOKEN)

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/CodeAnalysisLogs
    sudo pip install shiftleft-scan-reports
    slreporter -a sl-vue-az --branch $(Build.SourceBranchName) -o $(Build.ArtifactStagingDirectory)/CodeAnalysisLogs
    echo "Install the Security Scan extension from https://marketplace.visualstudio.com/items?itemName=shiftleftsecurity.sl-scan-results to view this report"
  displayName: 'Convert to SARIF'
  workingDirectory: '$(Build.SourcesDirectory)'
  env:
    SHIFTLEFT_ACCESS_TOKEN: $(SHIFTLEFT_ACCESS_TOKEN)
    WORKSPACE: https://github.com/HooliCorp/sl-vue/tree/$(Build.SourceVersion)

- task: PublishBuildArtifacts@1
  displayName: "Publish analysis logs"
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs"
    ArtifactName: "CodeAnalysisLogs"
    publishLocation: "Container"
